# Funding options for the project
# You can add your own funding methods here

# GitHub Sponsors
# github: [YOUR_USERNAME]

# PayPal
# custom: ["https://www.paypal.com/paypalme/YOUR_PAYPAL"]

# Ko-fi
# ko_fi: YOUR_KOFI

# Buy Me a Coffee
# custom: ["https://www.buymeacoffee.com/YOUR_USERNAME"]

# Patreon
# patreon: YOUR_PATREON

# Open Collective
# open_collective: YOUR_COLLECTIVE

# Note: Uncomment and update the relevant lines above with your funding information
# This file enables the "Sponsor" button on your GitHub repository

